name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  terraform:
    name: Terraform compliance
    runs-on: ubuntu-20.04
    container: hashicorp/terraform:1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform lint
        run: terraform fmt -check -recursive -diff .
