name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  terraform:
    name: Terraform lint, init, validate and plan based on module examples
    runs-on: ubuntu-20.04
    container: hashicorp/terraform:1.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Lint
        run: terraform fmt -check -recursive -diff .

      - name: Initialize
        run: terraform -chdir="services/webserver-cluster/examples/basic-example" init

      - name: Validate
        run: terraform -chdir="services/webserver-cluster/examples/basic-example" validate -no-color

      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir="services/webserver-cluster/examples/basic-example" plan
