name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  terraform:
    name: Terraform compliance
    runs-on: ubuntu-20.04
    container: hashicorp/terraform:1.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform lint
        run: terraform fmt -check -recursive -diff .

      - name: Define terraform directories
        run: |
          EXAMPLES_DIRS=( )
          EXAMPLES_DIRS+=( "services/webserver-cluster/examples/basic-example" )

      - name: Initialize terraform
        run: |
          for dir in "${EXAMPLES_DIRS[@]}"; do
            terraform -chdir="$dir" init
          done

      - name: Validate examples
        run: |
          for dir in "${EXAMPLES_DIRS[@]}"; do
            terraform -chdir="$dir" validate -no-color
          done
